config/routes.rb
Rails.application.routes.draw do

  resources :divisa_valors
  resources :divisas

  resources :categoris 
  resources :productos
  resources :users

  devise_for :usuarios
  root 'productos#index'
 


  resources :registros
  post 'registro', to: 'registros#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/parciales/_carrito.html.erb
<div class="center-xs text-center radio no-margin yiellow" style="width:35%">
      <div class="center-xs input-group sin-fondo">                   
             <h2><strong>Busca tu producto</strong></h2>
      <div class="center-xs input-group ">
            <%= search_form_for @q do |f| %>
               <input type="search" name="q[nombre_cont]" placeholder="Escribe aqui tu busqueda" class="form-control">
      </div>
      </div>
      <div class="center-xs input-group ">                   
            <div class="btn-group mr-2" role="group" aria-label="First group">
               <button type="f.submit" class="btn btn-secondary">Buscar</button>
            </div>  
            <% end %>
      </div>
      <div>
        <button event="@onclick"></button>
      </div>
      <br>
         <button type="button" class="btn btn-secondary"><a href="/productos/new">Añadir Producto Nuevo</a></button>
      <br>
      <div class="card text-white form yiellow radio sin-fondo">
          <div>
            <%= image_tag "logo.gif", size: "80x80"%>
          </div>

           <div class="card-title "> <h1>CARRITO</h1></div>
             <div class="card-body sin-fondo">
               <div class="center-xs text-center">
                  <h3 class="card-title"><td>PRODUCTOS</td></h3>
                  <table id="carrito" class="w-100">
                    <tr class="text-center">
                      <td><strong>NOMBRE</strong></td>
                      <td><strong>PRECIO</strong></td>
                      <td><strong>CANTIDAD</strong></td>
                    </tr>
                  </table>
               </div>
               <br>
               <div>
                  <h5>Total:</h5>
                  <h6 class="card-title"><strong class="total">0 Bs</strong></h5>
                  <ul>
                     <li></li>
                  </ul>
               </div>
               <br>
               <!-- <button type="submit" class="btn btn-secondary">Borrar item</button> -->
               <button type="submit" class="btn btn-secondary" id="resetcar">Reiniciar</button>
  </div>
</div>

app/views/parciales/_navegacion.html.erb
    <header>

      <nav class = "be-red large-padding center-xs" role="navigation" >

            <ul class= "row navbar box-sizing a col-md">
              <li class="col-md">
              <button type="button" class="btn btn-default navbar-btn"><%= link_to "Productos", productos_path %></button>
              </li> 

              <li class="col-md">
              <button type="button" class="btn btn-default navbar-btn"><%= link_to "Por Categorias", categoris_path %></button>
              </li> 


         <% unless usuario_signed_in? %>
              <li class="col-md">
              <button type="button" class="btn btn-default navbar-btn"><%= link_to "Iniciar Sesion", usuario_session_path %></button>
              </li>   
              <li class="col-md">
             <button type="button" class="btn btn-default navbar-btn"><%= link_to "Registrarme", new_usuario_registration_path %></button>
              </li>  
         <%end %>                

              <li class="col-md ">
           <button type="button" class="btn btn-default navbar-btn"> <%= link_to "Actualizar Precio de Divisas", new_divisa_valor_path %></button>
              </li>                    

                <% if usuario_signed_in? %>
              <li class="col-md ">
           <button type="button" class="btn btn-default navbar-btn"> <%= link_to "Cerrar Sesion", destroy_usuario_session_path, method: :delete %></button>
              </li>
              
                <%end %>

            </ul>
          
      <% unless DivisaValor.last == nil %>
      <p class="navbar-text arial">Ultima Actualizacion del dolar :</p><br>
      <P class="navbar-text greend arial"><%= number_with_delimiter(@divisa=DivisaValor.last.valor)%> Bs </P>
      <p class="arial"> <%= @divisa=DivisaValor.last.fecha %></p><br> 
      <%end %>
      </nav>

    </header>









      