config/routes.rb
Rails.application.routes.draw do

  resources :divisa_valors
  resources :divisas

  resources :categoris 
  resources :productos
  resources :users

  devise_for :usuarios
  root 'productos#index'
 


  resources :registros
  post 'registro', to: 'registros#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/categori.rb
class Categori < ApplicationRecord
	  has_many :Productos
end

app/controllers/categoris_controller.rb
class CategorisController < ApplicationController
  before_action :set_categori, only: [:show, :edit, :update, :destroy]

  # GET /categoris
  # GET /categoris.json
  def index
    @categoris = Categori.all
  end

  # GET /categoris/1
  # GET /categoris/1.json
  def show
    #@productos = Producto.all
    @productos = Producto.where("categori_id = ?", params[:id])
  end

  # GET /categoris/new
  def new
    @categori = Categori.new
  end

  # GET /categoris/1/edit
  def edit
  end

  # POST /categoris
  # POST /categoris.json
  def create
    @categori = Categori.new(categori_params)

    respond_to do |format|
      if @categori.save
        format.html { redirect_to categoris_path, notice: 'Divisa valor was successfully created.' }
        format.json { render :show, status: :created, location: @categori }
      else
        format.html { render :new }
        format.json { render json: @categori.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoris/1
  # PATCH/PUT /categoris/1.json
  def update
    respond_to do |format|
      if @categori.update(categori_params)
        format.html { redirect_to @categori, notice: 'Divisa valor was successfully updated.' }
        format.json { render :show, status: :ok, location: @categori }
      else
        format.html { render :edit }
        format.json { render json: @categori.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoris/1
  # DELETE /categoris/1.json
  def destroy
    @categori.destroy
    respond_to do |format|
      format.html { redirect_to categoris_url, notice: 'Divisa valor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categori
      @categori = Categori.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categori_params
      params.require(:categori).permit(:categoria)
    end
end

app/views/categoris/_form.html.erb
<div class="center-xs fondo">

      <%= form_with(model: categori, local: true) do |form| %>
        <% if categori.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(categori.errors.count, "error") %> Categoria no permitida</h2>

            <ul>
              <% categori.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>


        <div class="field white">
          <%= form.label :categoria , "NOMBRE DE LA CATEGORIA:"%>
          <%= form.text_field :categoria , class: "form-control" %>
        </div>

        <div class="actions white btn">
          <%= form.submit "Crear Categoria"%>
        </div>
      <% end %>

</div>

app/views/categoris/edit.html.erb
<h1>EDITAR CATEGORIA</h1>

<%= render 'form', categori: @categori %>

<%= link_to 'Mostrar', @categori %> |
<%= link_to 'Regresar', categoris_path %>

app/views/categoris/index.html.erb
<p id="notice"><%= notice %></p>
<div class=" center-xs sin-fondo">  
	<div class="row center-xs sin-fondo">
		      <% @categoris.each do |categori| %>
		<div class="card text-white bg-dark mb-3 no-margin radio" style="max-width: 18rem;">
		  <div class="card-header"> <h1><%= link_to categori.categoria.capitalize , categori %></h1></div>
		    <div class="card-body">

		    	<% id = categori.id %>

		      <h3 class="card-title"><td>Productos en esta categoria:</td></h3>
		      <h5 class="card-text"><strong><%=  Producto.where(categori_id:id).length %> </strong></h5>
		      <br>

		      <button class=""><%= link_to  "Editar Categoria", edit_categori_path(categori) %></button>
			  <button class=""><%= link_to  "Borrar categoria", categori, method: :delete, data: { confirm: 'Are you sure?' } %></button>
		    </div>
		</div>
		      <% end %>		
	</div>
</div>

<div class=" center-xs">
  <button class="a btn white"><%= link_to 'Crear Nueva Categoria', new_categori_path %></button>
  
</div>

app/views/categoris/new.html.erb
<div class= " needs-validation">
		<div class="row center-xs">
			<h1>INGRESE NUEVA CATEGORIA</h1>
		</div>

		<div class="row center-xs">
			<%= render 'form', categori: @categori %>
		</div>



		<div class="row center-xs">
			<h1 class="btn white"><%= link_to 'Regresar', categoris_path %></h1>
		</div>
</div>

app/views/categoris/show.html.erb
<div class="row fondo centrando center-xs">

	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Categoria:</strong>
	  <%= @categori.categoria %>
	</p>

	<%= link_to image_tag("lapiz.png", size: "30x30", :alt => "dolar feed"), edit_categori_path(@categori) %> |
	<h1></h1> <%= link_to 'Volver a las Categorias', categoris_path %></h1>
</div>

 <table class=" fondo centrando center-xs">
    <thead>
        
      <tr>
        <th>Nombre</th>
        <th>Categoria</th>
        <th>Unid por <br> display</th>
        <th> Precio <br> por unidad </th>  
        <th><%= image_tag("signodolar2.png", size: "35x35", :alt => "dolar feed") %><br>Caja</th>     
        <th><%= image_tag("signodolar2.png", size: "35x35", :alt => "dolar feed") %><br>Unidad</th>     
        <th colspan="3"></th>
      </tr>  


    </thead>


    <tbody>

      <% @productos.each do |producto| %>
        <tr class= "text-center">
          <td class="grande"><%= link_to producto.nombre, producto %></td>

            <% id = producto.categori %>
          <td><%= Categori.find_by(id:id).categoria %></td>

          <td><%= producto.cantidad_x_display %></td>
          <td class="red"><% if producto.PrecioUnidadBs == nil %>
              <h2><%= number_with_delimiter(((producto.precio.to_f * DivisaValor.last.valor)/producto.cantidad_x_display).round(-3))%>Bs </h2>
              <% else %>
              <h2><%= number_with_delimiter(((producto.precio.to_f * DivisaValor.last.valor)/producto.cantidad_x_display).round(-3))%>Bs </h2>
              <% end %>
          <td><h2 class="green"> $<%= (producto.precio).round(2) %> </h2></td>

          <td><h2 class="green"> $<%= (((producto.precio))/producto.cantidad_x_display).round(2) %> </h2></td>

          <td><%= link_to image_tag("lapiz.png", size: "50x50", :alt => "dolar feed"), edit_producto_path(producto) %></td>
          <td><%= link_to image_tag("papelera.png", size: "50x50", :alt => "dolar feed"), producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>