config/routes.rb
Rails.application.routes.draw do

  resources :divisa_valors
  resources :divisas

  resources :categoris 
  resources :productos
  resources :users

  devise_for :usuarios
  root 'productos#index'
 


  resources :registros
  post 'registro', to: 'registros#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/divisa.rb
class Divisa < ApplicationRecord
	has_many :DivisaValors
end

app/controllers/divisas_controller.rb
class DivisasController < ApplicationController
  before_action :set_divisa, only: [:show, :edit, :update, :destroy]

  # GET /divisas
  # GET /divisas.json
  def index
    @divisas = Divisa.all
  end

  # GET /divisas/1
  # GET /divisas/1.json
  def show
  end

  # GET /divisas/new
  def new
    @divisa = Divisa.new
  end

  # GET /divisas/1/edit
  def edit
  end

  # POST /divisas
  # POST /divisas.json
  def create
    @divisa = Divisa.new(divisa_params)

    respond_to do |format|
      if @divisa.save
        format.html { redirect_to @divisa, notice: 'Divisa was successfully created.' }
        format.json { render :show, status: :created, location: @divisa }
      else
        format.html { render :new }
        format.json { render json: @divisa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisas/1
  # PATCH/PUT /divisas/1.json
  def update
    respond_to do |format|
      if @divisa.update(divisa_params)
        format.html { redirect_to @divisa, notice: 'Divisa was successfully updated.' }
        format.json { render :show, status: :ok, location: @divisa }
      else
        format.html { render :edit }
        format.json { render json: @divisa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisas/1
  # DELETE /divisas/1.json
  def destroy
    @divisa.destroy
    respond_to do |format|
      format.html { redirect_to divisas_url, notice: 'Divisa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_divisa
      @divisa = Divisa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def divisa_params
      params.require(:divisa).permit(:nombre, :status)
    end
end

app/helpers/divisas_helper.rb
module DivisasHelper
end

app/views/divisas/_form.html.erb
<%= form_with(model: divisa, local: true) do |form| %>
  <% if divisa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(divisa.errors.count, "error") %> no permitieron que se guardara el registro:</h2>

      <ul>
        <% divisa.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status, class:"form-control" %>
  </div>

  <div>
    <button class="btn btn-secondary"><%= form.submit %></button>
  </div>
<% end %>

app/views/divisas/edit.html.erb
<h1>Editing Divisa</h1>

<%= render 'form', divisa: @divisa %>

<%= link_to 'Show', @divisa %> |
<%= link_to 'Back', divisas_path %>

app/views/divisas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="fondo center-xs text-center">
<h1>Divisas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @divisas.each do |divisa| %>
      <tr>
        <td><%= divisa.nombre %></td>
        <td><%= divisa.status %></td>
        <td><%= link_to 'Show', divisa %></td>
        <td><%= link_to 'Edit', edit_divisa_path(divisa) %></td>
        <td><%= link_to 'Destroy', divisa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button class="btn btn-secondary"><%= link_to 'New Divisa', new_divisa_path %></button>
</div>

app/views/divisas/new.html.erb
<div class="fondo">
	
<h1>New Divisa</h1>

<%= render 'form', divisa: @divisa %>

<button class="btn btn-secondary"><%= link_to 'Back', divisas_path %></button>

</div>

app/views/divisas/show.html.erb
<p id="notice"><%= notice %></p>
<div>
	
</div>

<div>
<p>
  <strong>Nombre:</strong>
  <%= @divisa.nombre %>
</p>
</div>
<div>
<p>
  <strong>Status:</strong>
  <%= @divisa.status %>
</p>
</div>
<%= link_to 'Edit', edit_divisa_path(@divisa) %> |
<%= link_to 'Back', divisas_path %>