config/routes.rb
Rails.application.routes.draw do

  resources :divisa_valors
  resources :divisas

  resources :categoris 
  resources :productos
  resources :users

  devise_for :usuarios
  root 'productos#index'
 


  resources :registros
  post 'registro', to: 'registros#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/divisa_valor.rb
class DivisaValor < ApplicationRecord
	belongs_to :divisa
end

app/controllers/divisa_valors_controller.rb
class DivisaValorsController < ApplicationController
  before_action :set_divisa_valor, only: [:show, :edit, :update, :destroy]

  # GET /divisa_valors
  # GET /divisa_valors.json
  def index
    @divisa_valors = DivisaValor.all
  end

  # GET /divisa_valors/1
  # GET /divisa_valors/1.json
  def show
  end

  # GET /divisa_valors/new
  def new
    @divisa_valor = DivisaValor.new
    #@divisas = Divisa.all
  end

  # GET /divisa_valors/1/edit
  def edit
  end

  # POST /divisa_valors
  # POST /divisa_valors.json
  def create
    @divisa_valor = DivisaValor.new(divisa_valor_params)

    respond_to do |format|
      if @divisa_valor.save
        format.html { redirect_to @divisa_valor, notice: 'Divisa valor was successfully created.' }
        format.json { render :show, status: :created, location: @divisa_valor }
      else
        format.html { render :new }
        format.json { render json: @divisa_valor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisa_valors/1
  # PATCH/PUT /divisa_valors/1.json
  def update
    respond_to do |format|
      if @divisa_valor.update(divisa_valor_params)
        format.html { redirect_to @divisa_valor, notice: 'Divisa valor was successfully updated.' }
        format.json { render :show, status: :ok, location: @divisa_valor }
      else
        format.html { render :edit }
        format.json { render json: @divisa_valor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisa_valors/1
  # DELETE /divisa_valors/1.json
  def destroy
    @divisa_valor.destroy
    respond_to do |format|
      format.html { redirect_to divisa_valors_url, notice: 'Divisa valor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_divisa_valor
      @divisa_valor = DivisaValor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def divisa_valor_params
      params.require(:divisa_valor).permit(:divisa_id, :fecha, :valor)
    end
end

app/helpers/divisa_valors_helper.rb
module DivisaValorsHelper
end

app/views/divisa_valors/_form.html.erb
<%= form_with(model: divisa_valor, local: true) do |form| %>
  <% if divisa_valor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(divisa_valor.errors.count, "error") %>no permitieron que se guardara el registro:</h2>

      <ul>
        <% divisa_valor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field white">
    <%= image_tag("signodolar2.png", size: "90x90", :alt => "dolar feed") %>
    <%= image_tag( "euro.png", size: "70x70", :alt => "euro feed") -%>
    <%= form.label :divisa_id %>
    <%= form.select("divisa_id", Divisa.all.collect {|p| [ p.nombre, p.id ] }, {include_blank: 'SELECCIONE'}) %>
  </div>

  <div class="field white">
    <%= form.label :fecha %>
    <%= form.date_select :fecha ,  class: "form-control"%>
  </div>

  <div class="field white">
    <%= form.label :valor , "Valor en Bs" %>
    <%= form.text_field :valor ,  class: "form-control"%>
  </div>

  <div class="actions white btn">
    <%= form.submit %>
  </div>
<% end %>

app/views/divisa_valors/edit.html.erb
<h1>Editing Divisa Valor</h1>

<%= render 'form', divisa_valor: @divisa_valor %>

<%= link_to 'Show', @divisa_valor %> |
<%= link_to 'Back', divisa_valors_path %>

app/views/divisa_valors/index.html.erb
<p id="notice"><%= notice %></p>
<div>
        

            <div class="col-md-5 p-lg-5 mx-auto my-5 radio">
              <h1 class="display-4 font-weight-normal">DOLAR DE HOY:</h1>
              <p class="navbar-text greend"><%= number_with_delimiter(@divisa=DivisaValor.last.valor) %> Bs</p>
              <br>
 


        
      <table>
        <thead>
          <tr>
            <th>Divisa</th>
            <th>Fecha</th>
            <th>Valor</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @divisa_valors.each do |divisa_valor| %>
            <tr>
              <td><%= divisa_valor.divisa_id %></td>
              <td><%= divisa_valor.fecha %></td>
              <td><%= divisa_valor.valor %></td>
              <td><%= link_to image_tag("ojo.png", size: "30x30", :alt => "dolar feed"), divisa_valor %></td>
              <td><%= link_to image_tag("lapiz.png", size: "30x30", :alt => "dolar feed"), edit_divisa_valor_path(divisa_valor) %></td>
              <td><%= link_to image_tag("papelera.png", size: "30x30", :alt => "dolar feed"), divisa_valor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      </div>
      <br>

</div>
<%= link_to 'New Divisa Valor', new_divisa_valor_path %>

app/views/divisa_valors/new.html.erb
<div class="needs-validation radio" style="width: 50%; margin: 0px 25%">
      <% if DivisaValor.last%>
	<div class="row center-xs radio">
		<h1 class=" w-100">Ultima Actualizacion: 
			<%= number_with_delimiter(@divisa=DivisaValor.last.valor)%> Bs
		</h1>
	<div class="radio">
		
		</div>
		  <%end %>
		  <br>
		<div class="row center-xs sin-fondo">
			<h1>Nueva actualizacion de divisa:</h1>
		</div>

		<div class="row center-xs sin-fondo">
			<%= render 'form', divisa_valor: @divisa_valor %>
		</div>


	</div>
	<button class="btn white"><%= link_to 'Regresar', divisa_valors_path %></button>
			
</div>

app/views/divisa_valors/show.html.erb
<div  style="width: 50%; margin: 0px 25%">
	<div class=" center-xs radio" >
		<div>
			<p id="notice"><%= notice %></p>
		</div>	
		
		<div>
			<h5>
			  <strong>Divisa:</strong>
			<% id = @divisa_valor.divisa_id %>
			<%= Divisa.find_by(id:id).nombre %>
			</h5>
		</div>
		<div>
			<h5>
			  <strong>Fecha:</strong>
			  <%= @divisa_valor.fecha %>
			</h5>
		</div>
		<div>
			<h5>
			  <strong>Valor en Bs:</strong>
			  <%= @divisa_valor.valor %>
			</h5>
		</div>
	</div>

	<div class="sin-fondo">
		<button class="btn white"><%= link_to "Editar", edit_divisa_valor_path(@divisa_valor) %></button>
		<button class="btn white"><%= link_to 'Regresar', divisa_valors_path %></button>
	</div>	
</div>